AR-11299 Updated docs for writing custom statuses
NextechSystems/selectapidocspub pull request #103
Opened 2021-01-14 15:39 UTC by ryan-novak-nextech

2021-01-14 19:49 UTC, JakeDriscoll requested changes
Need to have an additional sample for doing an appointment status query other than by `appointment-status/{id}`

2021-01-14 19:49 UTC, JakeDriscoll commented on source/includes/_appointmentstatus.md
> +| name | query | The name of the appointment status | N | _15.9_ |
Should put an example here of a search by name

2021-01-14 21:58 UTC, ryan-novak-nextech commented on source/includes/_appointmentstatus.md
> +| name | query | The name of the appointment status | N | _15.9_ |
I added another example. Also, I noticed as I was searching for other examples that appointment type doesn't quite match the formatting of some of our other sections, so I updated the formatting of status to be a bit closer to what we have in most of the rest of the docs.

2021-01-15 16:36 UTC, JakeDriscoll approved these changes
Looks good

2021-01-15 16:36 UTC, merged