Ar 15050 doc ref search documentation
NextechSystems/selectapidocspub pull request #129
Opened 2022-06-03 16:08 UTC by dustinbrinegar

DocumentReference documentation for Get by ID and $docref

2022-06-06 19:08 UTC, joerocca requested changes
We should also provide example for the `_id` GET and POST based search requests.

2022-06-06 19:08 UTC, joerocca commented on source_r4/includes/_documentReference.md
> +| identifier | Must be if the form `documenttype-id` i.e: GET /DocumentReference/history-5  | Yes | 16.8
While identifier is technically what gets sent to the anchor, that really isn't known to the caller. We should follow the GET by ID example of immunization (or another resource) and just include the located in column with the ID method param name provided above.
https://github.com/NextechSystems/selectapidocspub/blob/develop/source_r4/includes/_patient.md#get-2
![image](https://user-images.githubusercontent.com/10346184/172229063-1c3064bc-f8e1-4898-9ba3-ff441e575c51.png)

2022-06-06 19:08 UTC, joerocca commented on source_r4/includes/_documentReference.md
> +#### Body Fields
We should provide a request body example since it's not clear that this requires the `Hl7.Fhir.Model.Parameters` resource type in the body.

2022-06-06 19:08 UTC, joerocca commented on source_r4/includes/_documentReference.md
> +| parameter | This is an array of parameters which must include one patient parameter | Yes |
a hyperlink to the  `Hl7.Fhir.Model.Parameters` resource type would be helpful here.
http://www.hl7.org/fhir/parameters.html

2022-06-06 20:16 UTC, dustinbrinegar commented on source_r4/includes/_documentReference.md
> +`GET /DocumentReference/{docutmentType-id}`
Fixed

2022-06-06 20:17 UTC, dustinbrinegar commented on source_r4/includes/_documentReference.md
> +| parameter.patient | The patient the document is for | Yes |
"is" was the intended word here, but I could change the wording to be more clear

2022-06-06 20:22 UTC, dustinbrinegar commented on source_r4/includes/_documentReference.md
> +| identifier | Must be if the form `documenttype-id` i.e: GET /DocumentReference/history-5  | Yes | 16.8
So our STU3 documentation uses "identifier" and so does FHIR. I'd say it makes more sense to call this "identifier" because STU3 and FHIR use this to describe the field, while the "immunizationID" is only used internally by the controller. Also for R4 Patient, Location and Account all use "identifier"

STU3 Appointment Example: 
![image](https://user-images.githubusercontent.com/7471746/172241924-ebb73828-4000-44bd-bc6a-33f2311a57bf.png)
FHIR Example:
![image](https://user-images.githubusercontent.com/7471746/172241974-e41565f0-b9f0-410b-9fb2-357dd710d8db.png)

2022-06-06 20:24 UTC, dustinbrinegar commented on source_r4/includes/_documentReference.md
> +#### Body Fields
The example including the body begins on line 207. Should it be in another format?

2022-06-06 20:27 UTC, dustinbrinegar commented on source_r4/includes/_documentReference.md
> +| parameter | This is an array of parameters which must include one patient parameter | Yes |
Added

2022-06-06 20:35 UTC, joerocca commented on source_r4/includes/_documentReference.md
> +| parameter.patient | The patient the document is for | Yes |
My fault. I read this wrong. Thanks!

2022-06-06 20:45 UTC, joerocca commented on source_r4/includes/_documentReference.md
> +| identifier | Must be if the form `documenttype-id` i.e: GET /DocumentReference/history-5  | Yes | 16.8
That's a good call out. It looks like all the actual new documentation is not using identifier though (at least that I see). I know you said the R4 Patient, Location and Account all use "identifier", but that looks like it is just because that documentation was copied over from the STU3 documentation and since we have not worked on those resources yet, or they were worked on before we started adding documentation (Account), they have not been updated to reflect what we have been doing for R4. 

For example, STU3 and R4 location docs are the same:
https://github.com/NextechSystems/selectapidocspub/blob/develop/source/includes/_location.md
https://github.com/NextechSystems/selectapidocspub/blob/develop/source_r4/includes/_location.md

The new documentation that has mostly been added [here](https://github.com/NextechSystems/selectapidocspub/blob/develop/source_r4/includes/_patient.md) seems to not follow that pattern of using "identifier" from what I can tell.

2022-06-06 20:45 UTC, joerocca commented on source_r4/includes/_documentReference.md
> +#### Body Fields
Missed this. Thanks!

2022-06-22 20:01 UTC, joerocca approved these changes

2022-06-22 20:05 UTC, merged