Added managing orginization docs
NextechSystems/selectapidocspub pull request #130
Opened 2022-06-10 17:38 UTC by LeeBryant1

2022-06-13 14:15 UTC, VinnieMaida requested changes, later dismissed
In addition to the two minor things I mentioned, I also noticed these things:

1. While the STU3 docs don't seem to do this, it looks like some of our other r4 documentation specifically calls out the GET by ID capabilities for a given resource, like this example in the immunization r4 documentation: https://github.com/NextechSystems/selectapidocspub/blob/5fd9656959762f657f64ebc7cc18e3db175c2102/source_r4/includes/_patient.md#get-2
2. It looks like we've also tended to call out the POST-based search abilities in our r4 search documentation, both by saying `query or payload` in the `Parameters` table's `Located in` column and also by showing some POST-based search in the examples section. Here's an example of that in the immunization documentation: https://github.com/NextechSystems/selectapidocspub/blob/5fd9656959762f657f64ebc7cc18e3db175c2102/source_r4/includes/_patient.md#search-7
3. If we do end up supporting the `_id` search, like I mentioned in this comment on the PartnerAPI PR: https://github.com/NextechSystems/select-partnerapi/pull/169#discussion_r895671800. then we should probably add that search parameter to the documentation, too

2022-06-13 14:15 UTC, VinnieMaida commented on source_r4/includes/_location.md
> +| managingOrganization | The identifier of the location | [ManagingOrginization](http://hl7.org/fhir/us/core/STU3.1.1/StructureDefinition-us-core-location-definitions.html#Location.managingOrganizati
Looks like there's a typo here ("Managing**Orginization**"), and it looks like other places in our documentation lists the `Type` column for reference type fields like this in the form: `[Reference](http://hl7.org/fhir/R4/references.html#Reference) [(USCoreOrganizationProfile)](http://hl7.org/fhir/us/core/STU3.1.1/StructureDefinition-us-core-organization.html)` rather than directly linking to the FHIR US Core description of the field.

2022-06-13 14:15 UTC, VinnieMaida commented on source_r4/includes/_location.md
> +	 "managingOrganization": {
I mentioned it in a [comment on the PartnerAPI PR](https://github.com/NextechSystems/select-partnerapi/pull/169#discussion_r895705822), but I think this field is ultimately actually going to look something like:
```
"managingOrganization": {
        "reference": "Organization/1",
        "display": "someOrganizationName"
}
```

2022-06-15 20:58 UTC, VinnieMaida reviewed
Just a few minor things left, I think.

2022-06-15 20:58 UTC, VinnieMaida commented on source_r4/includes/_location.md
> +| identifier | The unique value assigned to each location which discerns it from all others | [Identifier](https://www.hl7.org/fhir/datatypes.html#Identifier) | _16.8_ |
Not related to this particular line, but to all of the fields in this table: technically the backend values that populate these fields have been around since whatever version(s) the STU3 endpoints were created under, so I think you could probably keep those versions the same here, though there's not exactly any harm in saying that you need one of the newer versions for this endpoint but, if we say that, we should probably say 16.9 instead of 16.8 (since the `_id` change you made is actually in 16.9)

2022-06-15 20:58 UTC, VinnieMaida commented on source_r4/includes/_location.md
> +| identifier | query or payload | The unique value assigned to each location which discerns it from all others |  No | _16.8_ |
Same comment as before about the version numbers in this table, except that `_id` is definitely only supported in 16.9, not 16.7

2022-06-17 21:05 UTC, joerocca approved these changes

2022-06-17 21:06 UTC, merged