AR-15053 added documentation around the new search params
NextechSystems/selectapidocspub pull request #154
Opened 2022-07-26 16:39 UTC by dustinbrinegar

2022-07-27 16:40 UTC, VinnieMaida requested changes
Just a few comments/thoughts.

2022-07-27 16:40 UTC, VinnieMaida commented on source_r4/includes/_documentReference.md
>  The supported types are history, emn and labs. history and labs share identifiers so history-5 and lab-5 will refer to the same document.
Was going to say that the `lab-` prefix referenced here is no longer a thing, but looks like Joe's PR takes care of fixing this, so nevermind: https://github.com/NextechSystems/selectapidocspub/pull/153/files

2022-07-27 16:40 UTC, VinnieMaida commented on source_r4/includes/_documentReference.md
>  | Name | Description | Required | Initial Version |
Technically pre-existing, and I don't know if it's maybe moreso something for Joe's PR that's currently up, but it looks like this and the other `Parameters` tables are missing the `Located in` table column.

2022-07-27 16:40 UTC, VinnieMaida commented on source_r4/includes/_documentReference.md
> +| patient | The patient associated with the document | No | 16.9
Should this maybe specify that it's the "ID of the patient" associated with the document? I guess it's kind of implied, but just to be specific.

2022-07-27 16:40 UTC, VinnieMaida commented on source_r4/includes/_documentReference.md
> +| category | The type of the document | No | 16.9
Technically `category` and `type` are two different fields in the DocumentReference, so this should probably say "the category of the document", specifically.

2022-07-27 16:40 UTC, VinnieMaida commented on source_r4/includes/_documentReference.md
> +GET https://select.nextech-api.com/api/r4/DocumentReference?_id=emn-557&type=11488-4&category=Unknown&date=2022-06-03&patient=26376357
It looks like the description of this example is now wrong. Additionally, I feel like it's probably not the most realistic example to have a search that searches by ID AND all of these other things, so maybe we should have this example be the ID search, and then add some other examples for the types of searches that we're required to support, that are outlined here: http://hl7.org/fhir/us/core/STU3.1.1/StructureDefinition-us-core-documentreference.html#mandatory-search-parameters

2022-07-27 16:40 UTC, VinnieMaida commented on source_r4/includes/_documentReference.md
> +<i><small>payload:</small></i>
Same comment here as my previous one about maybe splitting out some of these search examples.

2022-07-27 16:40 UTC, VinnieMaida commented on source_r4/includes/_documentReference.md
> +patient:26376357
I believe we're ideally only allowing GUIDs for patient IDs for the R4 STS calls, so might be better to use a GUID as an example here.

2022-07-27 20:15 UTC, dustinbrinegar commented on source_r4/includes/_documentReference.md
> +| category | The type of the document | No | 16.9
Fixed

2022-07-27 20:15 UTC, dustinbrinegar commented on source_r4/includes/_documentReference.md
> +| patient | The patient associated with the document | No | 16.9
Added some wording here to make it more clear

2022-07-27 20:16 UTC, dustinbrinegar commented on source_r4/includes/_documentReference.md
>  The supported types are history, emn and labs. history and labs share identifiers so history-5 and lab-5 will refer to the same document.
I did have this changed originally but I figured leaving it unchanged would make merging less likely to have a conflict

2022-07-27 21:06 UTC, VinnieMaida reviewed
Just a few more minor things!

2022-07-27 21:06 UTC, VinnieMaida commented on source_r4/includes/_documentReference.md
> +| _id | query or body | Must be in the form `documenttype-id` i.e: GET /DocumentReference?_id=history-5  | No | 16.8
I was going to say that I think we usually say `query or payload`, but it looks like we do have some r4 documentation that says "body" instead of payload, so this is probably fine. One really minor thing is that this table says "query or body" while the other search parameter table you changed says "body or query", so we should probably be consistent, whatever we say.

2022-07-27 21:06 UTC, VinnieMaida commented on source_r4/includes/_documentReference.md
> +| resourceType | body or query | Must be `Parameters` | Yes | 16.9 |
Since $docref is kind of a special operation, I'm not actually sure off-hand if its POST format supports parameters in either the URI or the body, like our other POST endpoints, though it might. All I really know that definitely works for it is the body parameters, though.

2022-07-27 21:06 UTC, VinnieMaida commented on source_r4/includes/_documentReference.md
> +| DocumentReferenceID | URI | Must be if the form `documenttype-id` i.e: GET /DocumentReference/history-5  | Yes | 16.8
Really minor, but it looks like previous documentation of ours for these GET by ID instances refer to the ID in the route as being in the `path` rather than `URI`.

2022-07-27 21:42 UTC, dustinbrinegar commented on source_r4/includes/_documentReference.md
> +| DocumentReferenceID | URI | Must be if the form `documenttype-id` i.e: GET /DocumentReference/history-5  | Yes | 16.8
Fixed

2022-07-27 21:42 UTC, dustinbrinegar commented on source_r4/includes/_documentReference.md
> +| resourceType | body or query | Must be `Parameters` | Yes | 16.9 |
Changed to just body to be safe

2022-07-27 21:42 UTC, dustinbrinegar commented on source_r4/includes/_documentReference.md
> +| _id | query or body | Must be in the form `documenttype-id` i.e: GET /DocumentReference?_id=history-5  | No | 16.8
I'm going to leave this, but yeah the example I used was body and I'll leave it for now because if we come to a consensus in the future for one way, it won't be hard to change

2022-07-27 21:42 UTC, dustinbrinegar commented on source_r4/includes/_documentReference.md
> +GET https://select.nextech-api.com/api/r4/DocumentReference?type=11488-4&category=Unknown&date=2022-06-03&patient=26376357
Fixed

2022-07-27 21:42 UTC, dustinbrinegar commented on source_r4/includes/_documentReference.md
> +#### Example: Search with all supported fields besides _id
Made the descriptions more detailed

2022-07-27 21:43 UTC, dustinbrinegar commented on source_r4/includes/_documentReference.md
> +patient:26376357
Fixed

2022-07-27 21:43 UTC, dustinbrinegar commented on source_r4/includes/_documentReference.md
> +GET https://select.nextech-api.com/api/r4/DocumentReference?_id=emn-557&type=11488-4&category=Unknown&date=2022-06-03&patient=26376357
Fixed

2022-07-28 12:01 UTC, VinnieMaida reviewed
I think we should maybe just consider using the same consolidated approach for the search documentation that a lot of the other R4 documentation is using but, other than that, things look good!

2022-07-28 19:51 UTC, VinnieMaida commented
One other thing: The $docref example response in this documentation uses an integer value for the `category.coding.code` value, but I think, with the recent backend changes made by the corresponding nx PR of yours, that this can be changed to instead be the category name.

2022-07-28 20:27 UTC, VinnieMaida commented on source_r4/includes/_documentReference.md
> +| Name | Located in | Description | Required | Initial Version |
Since this is now just one table, I think the "Located in" column should probably say "query or payload" or "query or body". Also, it looks like the `GET /DocumentReference?{parameters}` and `POST /DocumentReference/_search` lines are side-by-side when you view the markdown, instead of on their own, separate bullet-pointed lines like the other examples.

Lastly, it looks like the "Note: The possible filter values for date are: `eq, `ne`, `le`, `lt`, `ge`, and `gt`" blurb below the parameters table is missing.

2022-07-28 23:38 UTC, VinnieMaida approved these changes
Still a minor visual oddity when the markdown documentation is viewed, but it is minor, and I'm out tomorrow, and everything else seems good, so I'll go ahead and merge this.

![image (3)](https://user-images.githubusercontent.com/18010552/181654600-2ec3cf48-ba93-45e4-8cf4-4f9dd3dea3d0.png)

2022-07-28 23:38 UTC, merged