AR-15704 Add Provenance to Document Reference
NextechSystems/selectapidocspub pull request #157
Opened 2022-08-12 19:47 UTC by MichaelFye-nx

Updates the DocumentReference documentation to include the updates for Provenance.
This also moves the r4 documentation for DocumentReference into the `patient` bulk documentation

2022-08-12 21:06 UTC, VinnieMaida requested changes
In addition to these things I mentioned, I think we should actually delete the file at https://github.com/NextechSystems/selectapidocspub/blob/develop/source_r4/includes/_documentReference.md, once we have all of those changes ported over.

2022-08-12 21:06 UTC, VinnieMaida commented on source_r4/includes/_patient.md
> +#### Search By POST Request
I don't think we need this POST search specific section, and can instead just combine it with the GET search section, like the original document did.

2022-08-12 21:06 UTC, VinnieMaida commented on source_r4/includes/_patient.md
> +The supported types are history, emn and labs. history and labs share identifiers so history-5 and lab-5 will refer to the same document.
Looks like this is another case where the supported document type section doesn't match the original document.

2022-08-12 21:06 UTC, VinnieMaida commented on source_r4/includes/_patient.md
> +    "identifier": [
Looks like this example response doesn't quite match the original.

2022-08-12 21:06 UTC, VinnieMaida commented on source_r4/includes/_patient.md
> +| type | Specifies the particular kind of document referenced (e.g. History and Physical, Discharge Summary, Progress Note). This usually equates to the purpose of making the document referenced. LOI
Not related to this particular line, but this table seems to reference `extension` fields that aren't actually supported, which the original document excluded, and also I think the 12.x version numbers are probably wrong.

2022-08-12 21:06 UTC, VinnieMaida commented on source_r4/includes/_patient.md
> +    "extension": [
I think this extension part can probably be removed.

2022-08-12 21:06 UTC, VinnieMaida commented on source_r4/includes/_patient.md
> +    "resourceType": "Bundle",
Looks like this example doesn't quite line up with the original document's example.

2022-08-16 14:06 UTC, MichaelFye-nx commented on source_r4/includes/_patient.md
>  | masteridentifier | The unique identifier assigned to each documentreference | [Identifier](https://www.hl7.org/fhir/datatypes.html#Identifier) | _12.7_ |
The validators in `ModelValidation.cs` at least do allow for `document-publish-portal` extensions, which is converted to `DocumentReferenceCommit.PublishToPortal`, which is then supported in `Hihstory.HistoryAPI.AttachFile()` in the input parameters

2022-08-16 14:07 UTC, MichaelFye-nx commented on source_r4/includes/_patient.md
> +| _revinclude | Must be `Provenance:target`. This enables requesting additional `Provenance` resources that relate to each document reference | No | 16.9 |
Ah, yes it would be 17.0, I still have the last version in my mind from scope closing

2022-08-16 14:13 UTC, MichaelFye-nx commented on source_r4/includes/_patient.md
> +    "extension": [
Why would this extension part be removable, since we support both of these extensions?

2022-08-16 14:22 UTC, VinnieMaida commented on source_r4/includes/_patient.md
>  | masteridentifier | The unique identifier assigned to each documentreference | [Identifier](https://www.hl7.org/fhir/datatypes.html#Identifier) | _12.7_ |
Ah, good call! I believe the R4 DocumentReference create/POST code had to change from where it previously was just re-utilizing the pre-existing STU3 backend method to instead use a new, R4-specific method, so I thought the support for extensions was lost when we switched to using a new backend method, since they're not strictly required for the regulatory work we're doing, but you're right that it looks like the current  code is indeed still checking for both the `note-category` and `document-publish-portal` extensions and then potentially passing values from those extensions to the backend R4 attach function, so good call, it looks like those extensions are technically supported! That said, since they're being passed to a new backend endpoint specifically for R4, I think the version of the extension support is still wrong.

2022-08-16 14:25 UTC, MichaelFye-nx commented on source_r4/includes/_patient.md
>  | masteridentifier | The unique identifier assigned to each documentreference | [Identifier](https://www.hl7.org/fhir/datatypes.html#Identifier) | _12.7_ |
Ah I honestly did forget that the anchor endpoint changed, I remembered reusing the same history methods, but missed that (which is even worse since I'm the bloke who wrote it 😆 )

2022-08-16 14:25 UTC, VinnieMaida commented on source_r4/includes/_patient.md
> +    "extension": [
Ah, good call, see this comment for more detail on why I was thinking that extensions were no longer supported in the R4 DocumentReference creation stuff: https://github.com/NextechSystems/selectapidocspub/pull/157/files#r946844025. Though I do think we should consider removing the `note-category` extension value from the example, even though it's technically supported, in favor of callers using the more "official" R4 DocumentReference category field in the POST body.

2022-08-16 15:29 UTC, MichaelFye-nx commented on source_r4/includes/_patient.md
> +    "extension": [
That is a good call, but it might be instead more valuable to keep the extension documented, and add a note indicating the preferred method and that that this extension is a legacy extension, really only intended for legacy support (i.e an integrator wants to reuse some existing codebase that they've made or otherwise). I've never particularly liked "hiding" features of an API, but I can certainly see the value in removing it altogether

2022-08-16 15:38 UTC, VinnieMaida commented on source_r4/includes/_patient.md
> +    "extension": [
Yeah, I think that approach would be fine, too. I was personally surprised to see we're supporting both the category extension and the official category field in the R4 POST, since that seems to further complicate and confuse things (and it looks like the current logic is that the extension overrides the official field, if the extension's present, which is really weird), but it is technically usable, so I can see the value in keeping and adding a note about the official category field (and maybe about which field is used in the event that they're both provided, too).

2022-08-16 15:42 UTC, MichaelFye-nx commented on source_r4/includes/_patient.md
> +    "extension": [
My thoughts exactly. Another option of course is we change the r4 endpoint  to no longer support the note category extension, and force the new FHIR property, but that would probably be the least user friendly route

2022-08-16 17:51 UTC, MichaelFye-nx commented on source_r4/includes/_patient.md
> +    "resourceType": "Bundle",
I've updated the example response to match the latest response format I've received

2022-08-16 17:52 UTC, MichaelFye-nx commented on source_r4/includes/_patient.md
> +    "extension": [
I've updated this to keep the nextech extension for note-category, but detailed a) the desire to use FHIR going forward, b) the fact that only the first FHIR category will be used, and c) when both are included, the extension note-category is used

2022-08-16 17:57 UTC, MichaelFye-nx commented on source_r4/includes/_patient.md
> +    "identifier": [
I've updated this to match the latest return format from partner api

2022-08-16 18:02 UTC, MichaelFye-nx commented on source_r4/includes/_patient.md
> +A reference to a document of any kind for any purpose. Provides metadata about the document so that the document can be discovered and managed. The scope of a document is any seralized object with a
Corrected this typo

2022-08-16 18:26 UTC, MichaelFye-nx commented on source_r4/includes/_patient.md
> +#### HTTP Request
Post search functionality documented from original r4 file

2022-08-16 18:26 UTC, MichaelFye-nx commented on source_r4/includes/_patient.md
> +| _id | Must be if the form `documenttype-id` i.e: GET /DocumentReference?_id=history-5  | Yes | 16.8 |
Added the missing search fields

2022-08-16 18:27 UTC, MichaelFye-nx commented on source_r4/includes/_patient.md
> +#### Example: Get the history document with ID 7741
Added the missing examples

2022-08-16 18:30 UTC, MichaelFye-nx commented on source_r4/includes/_patient.md
> +| type | Specifies the particular kind of document referenced (e.g. History and Physical, Discharge Summary, Progress Note). This usually equates to the purpose of making the document referenced. LOI
As noted elsewhere, since we do actually support both of these, I've left the documentation of the extensions, and added notes about how the note-category extension should be handled

2022-08-16 19:56 UTC, VinnieMaida reviewed
Just a few more things that I noticed, though admittedly a lot of them are pre-existing.

2022-08-16 19:56 UTC, VinnieMaida commented on source_r4/includes/_patient.md
> +    "identifier": [
Maybe it's your setup, but it looks like the response in the original R4 documentation example had more fields to it (`context.encounter`, for example), so I think it would probably be better to just copy that one over.

2022-08-16 19:56 UTC, VinnieMaida commented on source_r4/includes/_patient.md
> +`GET /DocumentReference?{parameters}`
Looks like this is pre-existing, but these request URL examples should probably have `r4/` prepended to them. It looks like that's done in other areas of the R4 documentation for some other resources.

2022-08-16 19:56 UTC, VinnieMaida commented on source_r4/includes/_patient.md
> +* Note: The `note-category` NexTech extension should not be used, instead the FHIR Category is encouraged
Really minor, but looks like this description is missing some periods. I also wonder if the FHIR category references should be `category`, complete with the code markdown tags.

2022-08-16 19:56 UTC, VinnieMaida commented on source_r4/includes/_patient.md
> +                    "system": "http://hl7.org/fhir/us/core/CodeSystem/us-core-documentreference-category",
I think it would probably be a little more fitting to use our custom `https://select.nextech-api.com/api/structuredefinition/note-category` system for the category code, since this one here is a special system that's only returned/used for EMN clinical notes, and that's not the type of document callers would be POSTing.

2022-08-16 19:56 UTC, VinnieMaida commented on source_r4/includes/_patient.md
> +    "context": {"encounter": {"reference": "[base]/Encounter/1"} },
It looks like other reference member showed in our example documentation don't have this `[base]` in front of it.

2022-08-16 19:56 UTC, VinnieMaida commented on source_r4/includes/_patient.md
> +`POST /DocumentReference/$docref`
Should probably prepend `r4/` to this URL.

2022-08-16 19:56 UTC, VinnieMaida commented on source_r4/includes/_patient.md
> +`GET /DocumentReference/$docref?{patient}[&{start}][&{end}]`
Looks like `r4` is missing from the URL here.

2022-08-16 19:56 UTC, VinnieMaida commented on source_r4/includes/_patient.md
> +The Medication Request resource can be used to record a patient�s medication prescription or order.
Not sure what this change is about.

2022-08-16 19:56 UTC, VinnieMaida commented on source_r4/includes/_patient.md
> +                "category": [
I think it would be slightly more fitting to return something like what the original document was returning, exact with the actual category name being something related to CCDAs, maybe, since this example here uses an integer as the `code`, which is no longer the case, I believe:
```
 "category": [
                    {
                        "coding": [
                            {
                                "system": "https://select.nextech-api.com/api/structuredefinition/note-category",
                                "code": "Prescriptions",
                                "display": "Prescriptions"
                            }
                        ],
                        "text": "Prescriptions"
                    }
                ],
```

2022-08-16 19:59 UTC, MichaelFye-nx commented on source_r4/includes/_patient.md
> +| type | Specifies the particular kind of document referenced (e.g. History and Physical, Discharge Summary, Progress Note). This usually equates to the purpose of making the document referenced. LOI
Wow I didn't see that  😆 .  I'll fix that in  a jiffy

2022-08-16 20:00 UTC, MichaelFye-nx commented on source/includes/_patient.md
> +Note: This custom extension should not be used, instead the FHIR Category is encouraged
Ah I must have copied it into the wrong window by mistake

2022-08-17 11:29 UTC, MichaelFye-nx commented on source_r4/includes/_patient.md
> +`GET /DocumentReference?{parameters}`
I've gone through and added the `r4/` prefix

2022-08-17 11:37 UTC, MichaelFye-nx commented on source_r4/includes/_patient.md
> +| Name | Description | Required | Initial Version |
Added the `Located in` column and fleshed out the fields that were missing this

2022-08-17 11:39 UTC, MichaelFye-nx commented on source_r4/includes/_patient.md
> +The `_revinclude` parameter allows support for including Provenance references that match the returned document references.
True, it is in the table above. However that table also neglects that our current validation will result in an error thrown if the value of `_revinclude` is not `Provenance:target`, so I have added that here

2022-08-17 11:40 UTC, MichaelFye-nx commented on source_r4/includes/_patient.md
> +POST https://select.nextech-api.com/api/r4/DocumentReference
Updated this

2022-08-17 11:42 UTC, MichaelFye-nx commented on source_r4/includes/_patient.md
> +`GET /DocumentReference/{documentType-id}`
This has been corrected

2022-08-17 11:46 UTC, MichaelFye-nx commented on source_r4/includes/_patient.md
> +    "identifier": [
Copied over the original, and it probably is  a setup difference in the document I requested

2022-08-17 11:46 UTC, MichaelFye-nx commented on source_r4/includes/_patient.md
> +`POST /DocumentReference`
Added `r4/`

2022-08-17 11:57 UTC, MichaelFye-nx commented on source_r4/includes/_patient.md
> +* Note: The `note-category` NexTech extension should not be used, instead the FHIR Category is encouraged
I noted it as markdown, and also added the `category` to the body fields, as this was missing

2022-08-17 11:59 UTC, MichaelFye-nx commented on source_r4/includes/_patient.md
> +                    "system": "http://hl7.org/fhir/us/core/CodeSystem/us-core-documentreference-category",
Updated this with a more appropriate category

2022-08-17 11:59 UTC, MichaelFye-nx commented on source_r4/includes/_patient.md
> +    "context": {"encounter": {"reference": "[base]/Encounter/1"} },
Removed [base]

2022-08-17 11:59 UTC, MichaelFye-nx commented on source_r4/includes/_patient.md
> +`POST /DocumentReference/$docref`
Added `r4/`

2022-08-17 11:59 UTC, MichaelFye-nx commented on source_r4/includes/_patient.md
> +`GET /DocumentReference/$docref?{patient}[&{start}][&{end}]`
Added `r4/`

2022-08-17 12:01 UTC, MichaelFye-nx commented on source_r4/includes/_patient.md
> +The Medication Request resource can be used to record a patient�s medication prescription or order.
Honestly not  sure either, looks like some funky encoding change

2022-08-17 12:23 UTC, VinnieMaida reviewed
Just a handful more minor things, other than one of the tables being rendered weird now.

2022-08-17 12:23 UTC, VinnieMaida commented on source_r4/includes/_patient.md
> +| type | Specifies the particular kind of document referenced (e.g. History and Physical, Discharge Summary, Progress Note). This usually equates to the purpose of making the document referenced. LOI
While the text says "CodeableConcept" here, the link is actually to a backbone element, so the link should probably be to `http://hl7.org/fhir/R4/datatypes.html#CodeableConcept`, instead.

2022-08-17 12:23 UTC, VinnieMaida commented on source_r4/includes/_patient.md
> +| context.encounter | The clinical context in which the document was prepared. | [Reference(US Core Encounter Profile)](https://www.hl7.org/fhir/references.html) | _16.8_ |
I feel like other areas of our R4 documentation that have text referencing a US Core profile have a link both to the FHIR "Reference" type and a specific link to the US Core profile indicated, but we're probably inconsistent about that, admittedly.

2022-08-17 12:23 UTC, VinnieMaida commented on source_r4/includes/_patient.md
> +| Name | Located in | Description | Required | Initial Version |
Not immediately sure why, but it looks like the appearance of this table somehow is now mangled, when you render the markdown file:
![image](https://user-images.githubusercontent.com/18010552/185115209-2e792309-b3b7-4703-803a-6282f6bb39ea.png)

2022-08-17 12:23 UTC, VinnieMaida commented on source_r4/includes/_patient.md
> +#### Example Search by _id in POST Body
While this example looks good now, it looks like there was another example right after this in the original R4 documentation: "Example Searching for all documents that have a type of 11488-4, category of Clinical, created before 2022-06-03 for the specific patient" which wasn't copied over here.

2022-08-17 12:23 UTC, VinnieMaida commented on source_r4/includes/_patient.md
> +| DocumentReferenceID | Must be if the form `documenttype-id` i.e: GET /r4/DocumentReference/history-5  | Yes | 16.8
Minor, and pre-existing, but I belatedly noticed here that the table here references `DocumentReferenceID`, but the placeholder ID route parameter is instead called `{documentType-id}`.

2022-08-17 12:23 UTC, VinnieMaida commented on source_r4/includes/_patient.md
> +                "category": [
I wonder if out example custom category code/description here should be some fake CCDA category name or something, rather than "Prescriptions", since that doesn't exactly line up with the category you'd think a CCDA would have.

2022-08-17 12:26 UTC, MichaelFye-nx commented on source_r4/includes/_patient.md
> +| type | Specifies the particular kind of document referenced (e.g. History and Physical, Discharge Summary, Progress Note). This usually equates to the purpose of making the document referenced. LOI
Corrected these cases where codeable concept referenced the wrong FHIR url

2022-08-17 12:31 UTC, MichaelFye-nx commented on source_r4/includes/_patient.md
> +| context.encounter | The clinical context in which the document was prepared. | [Reference(US Core Encounter Profile)](https://www.hl7.org/fhir/references.html) | _16.8_ |
Ah you're right, it does do a double link to reference and the profile. I've fixed that here

2022-08-17 12:33 UTC, MichaelFye-nx commented on source_r4/includes/_patient.md
> +#### Example Search by _id in POST Body
Found the missed reference

2022-08-17 12:39 UTC, MichaelFye-nx commented on source_r4/includes/_patient.md
> +| DocumentReferenceID | Must be if the form `documenttype-id` i.e: GET /r4/DocumentReference/history-5  | Yes | 16.8
Updated parameter name

2022-08-17 13:44 UTC, VinnieMaida reviewed
Last few things, I swear!

2022-08-17 13:44 UTC, VinnieMaida commented on source_r4/includes/_patient.md
> +| custodian | Identifies the organization or group who is responsible for ongoing maintenance of and access to the document. | [Reference(USCoreOrganizationProfile)](https://www.hl7.org/fhir/referenc
Not to open up a whole other can of worms, but this field (and probably others in this section) is another case of where we're missing the link to the US core profile.

2022-08-17 13:44 UTC, VinnieMaida commented on source_r4/includes/_patient.md
> +POST https://select.nextech-api.com/api/r4/DocumentReference
Looks like the `/_search` is missing from this example.

2022-08-17 13:44 UTC, VinnieMaida commented on source_r4/includes/_patient.md
> +| category | Allows setting category of the document  | No | _16.8 |
Looks like you're missing a `_` at the end of the version cell here.

2022-08-17 14:35 UTC, VinnieMaida reviewed
Other than these two things, if we're not doing a blanket version blurb somewhere as part of this item, then I feel like the "Fields" table shouldn't have any fields in it with a `12.x` version, because you shouldn't ever be able to call into an R4 DocumentReference endpoint of any kind on that version.

2022-08-17 14:35 UTC, VinnieMaida commented on source_r4/includes/_patient.md
>  | Name | Description | Type | Initial Version |
I belatedly noticed that the following DocumentReference response fields aren't documented here at all:
- status
- category
- content.attachment.data
- content.attachment.format
- context.period

2022-08-17 14:35 UTC, VinnieMaida commented on source_r4/includes/_patient.md
> +| subject | The patient pertaining to the documentreference | [Reference](https://www.hl7.org/fhir/R4/references.html) ( [Patient])(http://hl7.org/fhir/us/core/STU3.1.1/StructureDefinition-us-core-pa
It looks like there's something slightly up with the markdown styling for all of these US core profile links:
![image](https://user-images.githubusercontent.com/18010552/185162244-8fe5c135-d681-43b4-93bc-807a48d60ef6.png)

2022-08-17 15:17 UTC, VinnieMaida approved these changes
Looks great to me now! Thanks for taking the time to fix all of that up!

2022-08-17 15:17 UTC, merged