Ar 15848 auth section update
NextechSystems/selectapidocspub pull request #169
Opened 2022-10-03 16:45 UTC by dustinbrinegar

This should cover everything required authorization wise for https://nextech1.sharepoint.com/:w:/r/sites/CuresCertificationResources/_layouts/15/Doc.aspx?sourcedoc=%7B84A32544-9079-4A1F-9609-D942BCF8C336%7D&file=(g)(10)%20API%20Documentation%20Checklist%2026Sep2022.docx&action=default&mobileredirect=true

Also this will need to be updated with production URLs once those are available

2022-10-03 22:46 UTC, JakeDriscoll commented
Since you made the auto its own file you're going to have to modify the docs to load this new md

2022-10-04 12:21 UTC, JakeDriscoll commented on source/includes/r4/_authorization.md
> +**Note: TLS 1.2 or higher and PKCE S256 are both required when using User Authentication**
TLS 1.2 is required for any and all traffic.

2022-10-04 12:23 UTC, JakeDriscoll commented on source/includes/r4/_authorization.md
> +| code_challenge_method | Always `S256` this indicates the code challenge will use SHA-256 for hashing |
Might be useful to make an Example column?

2022-10-04 12:24 UTC, JakeDriscoll commented on source/includes/r4/_authorization.md
> +### Authorization With Postman ###
Should probably be worded `Example of Authorization With Postman`. In the end this is not how consuming applications are going to use our STS service.

2022-10-04 12:25 UTC, JakeDriscoll commented on source/includes/r4/_authorization.md
> +1. Auth URL should be set to https://mypatientvisit-sts-dev.azurewebsites.net/connect/authorize
Shouldn't this be `https://mypatientvisit-sts-dev.azurewebsites.net/connect/authorize?aud=<your audience here>` ?

2022-10-04 12:25 UTC, JakeDriscoll commented on source/includes/r4/_authorization.md
> +1. Secret should be set to the value given to you by Nextech. NOTE: This should be stored securely and access to it highly limited
This is definitely not a `should` this is a `must`

2022-10-04 12:28 UTC, JakeDriscoll commented on source/includes/r4/_authorization.md
> +launch/patient openid fhirUser offline_access patient/Medication.read patient/AllergyIntolerance.read patient/CarePlan.read patient/CareTeam.read patient/Condition.read patient/Device.read patient/Di
This single line looks pretty ugly, should we at least throw it into a bulleted list? Or something better?

Maybe even just a link out to SMART on Fhir scopes. Here is an example: https://smilecdr.com/docs/smart/smart_on_fhir_scopes.html#picking-scopes

2022-10-04 12:29 UTC, JakeDriscoll commented on source/includes/r4/_gettingstarted.md
> +**Response Parameters**
This all seems like duplicated information now if we are having a whole Auth section.

2022-10-04 12:29 UTC, JakeDriscoll commented on source/includes/r4/_gettingstarted.md
> +Note: See the Authorization section for more information
Provide a link

2022-10-04 12:30 UTC, JakeDriscoll requested changes
I noted a handful of things, but I'm also not sold on the idea of making `_authorization.md` it's own file, you have to look at what it's going to look like when published.

2022-10-04 12:31 UTC, JakeDriscoll commented
We also need to list the different types of roles Patient/Practitioner/System etc.

2022-10-05 01:28 UTC, dustinbrinegar commented on source/includes/r4/_authorization.md
> +**Note: TLS 1.2 or higher and PKCE S256 are both required when using User Authentication**
Fixed

2022-10-05 01:29 UTC, dustinbrinegar commented on source/includes/r4/_authorization.md
> +### Authorization With Postman ###
Changed

2022-10-05 01:29 UTC, dustinbrinegar commented on source/includes/r4/_authorization.md
> +1. Auth URL should be set to https://mypatientvisit-sts-dev.azurewebsites.net/connect/authorize
I'm not sure, and wasn't able to figure out a definite answer, and both ways seem to work fine for dev sts

2022-10-05 01:29 UTC, dustinbrinegar commented on source/includes/r4/_authorization.md
> +1. Secret should be set to the value given to you by Nextech. NOTE: This should be stored securely and access to it highly limited
Fixed

2022-10-05 01:29 UTC, dustinbrinegar commented on source/includes/r4/_authorization.md
> +launch/patient openid fhirUser offline_access patient/Medication.read patient/AllergyIntolerance.read patient/CarePlan.read patient/CareTeam.read patient/Condition.read patient/Device.read patient/Di
Made it a list

2022-10-05 01:29 UTC, dustinbrinegar commented on source/includes/r4/_gettingstarted.md
> +**Response Parameters**
Yeah I saw this but I removed the existing auth section stuff and placed it into the stand alone file, but didn't know if it should be part of this item to clean that up too since it was preexisting in that section

2022-10-05 01:29 UTC, dustinbrinegar commented on source/includes/r4/_gettingstarted.md
> +Note: See the Authorization section for more information
Fixed

2022-10-05 01:39 UTC, dustinbrinegar commented
> We also need to list the different types of roles Patient/Practitioner/System etc.

Added these. I could only find `system/*.read` as our only system scope currently, not 100% if we're going to use this going forward or if we'll have a system scope for every endpoint.

> I noted a handful of things, but I'm also not sold on the idea of making `_authorization.md` it's own file, you have to look at what it's going to look like when published.
I think it should look fine, but it's a pretty quick change to consolidate it into one file if it looks clunky. I do think people are going to spin their wheels for a really long time on getting auth to work which is why I want to make it easily findable. A ton of API complaints were just people struggling to get auth to work and having it's own section should help when they browse the documentation

2022-10-05 13:02 UTC, JakeDriscoll commented on source/includes/r4/_gettingstarted.md
> +**Response Parameters**
What point is it in having duplicated information?

2022-10-05 13:05 UTC, JakeDriscoll commented on source/includes/r4/_authorization.md
> +| code_challenge_method | Always `S256` this indicates the code challenge will use SHA-256 for hashing |
This is a code review and you're writing new documentation for a new process, do what is right, not what was done.

2022-10-05 13:10 UTC, JakeDriscoll commented on source/includes/r4/_authorization.md
> +**Note: TLS 1.2 and PKCE S256 are both required when using User Authentication**
I think you missed my previous comment. TLS 1.2 is required for all communications, not just for authentication.

2022-10-06 19:28 UTC, VinnieMaida commented on source/includes/r4/_partnerAuthorization.md
> +Nextech's implementation of the FHIR® standard is protected by the [OAuth 2.0 standard](https://oauth.net/2/) for authenticating requests. All API requests are authenticated by passing a Bearer token
I just used what the previous documentation used, but I agree that the RFC link is better, so I changed it in all of the places I noticed.

2022-10-06 19:30 UTC, VinnieMaida commented on source/includes/r4/_smartAppAuthorization.md
> +1. `Code Challenge Method` should be `SHA-256`
This seems to be describing the values you should see in Postman and, at least for my Postman version, my `Code Challenge Method` dropdown shows the option as `SHA-256`, not `S256`. There is a separate part of the documentation that uses `S256` for a PKCE-related URL parameter, though.

2022-10-06 19:41 UTC, dustinbrinegar commented on source/includes/r4/_smartAppAuthorization.md
> +1. `Code Challenge Method` should be `SHA-256`
Good point this is postman. Would it make sense to add: "Note: "SHA-256 is what postman uses, but 'S256' is the actual value being used". My concern is users will skim the example, put SHA-256 in a different tool like cURL and be confused why it's not working.

2022-10-06 19:48 UTC, VinnieMaida commented on source/includes/r4/_smartAppAuthorization.md
> +1. `Code Challenge Method` should be `SHA-256`
This is pretty explicitly an example for Postman, so if someone reading it tries to apply it to another tool then I'd think that's their fault, personally. 🙂

2022-10-07 12:58 UTC, JakeDriscoll approved these changes

2022-10-07 14:43 UTC, merged