AR-3270 adding documentation for Patient Type resource
NextechSystems/selectapidocspub pull request #57
Opened 2018-10-16 19:26 UTC by JakeDriscoll

@dustinlange @stullis @jsmet @JGruberNXT 

Added patient-type docs

2018-10-17 12:56 UTC, VinnieMaida requested changes
Noticed too minor copy/paste things.

2018-10-17 12:56 UTC, VinnieMaida commented on source/includes/_patienttype.md
> +`GET /appointment-type?{parameters}`
This says "appointment-type" here. Assume it's a copy/paste issue.

2018-10-17 12:56 UTC, VinnieMaida commented on source/includes/_patienttype.md
> +#### Example: Get a specific location based on identifier
This mentions "location" rather than patient type.

2018-10-17 14:44 UTC, dustinlange commented on source/includes/_patienttype.md
> +The patient type resource contains information about a patient and their releation to the practice. Examples include new patient, prospect, deceased.
Typo...releation -> relation

2018-10-17 15:21 UTC, JGruberNXT commented on source/includes/_patienttype.md
> +The patient type resource contains information about a patient and their relation to the practice. Examples include new patient, prospect, deceased.
I don't think these are typical of what people use this field for, and will probably be confusing with patient-status because of the patient/prospect stuff.   Deceased may be one they use.   I would either ask Meikin for a couple examples or pull from our minimal set, as I think these have evolved over the years.  For instance, I think people used to have like "Collections" in there for people sent to collections, but now that we have collections, I'm not sure they use it for that anymore

2018-10-17 18:20 UTC, JakeDriscoll commented on source/includes/_patienttype.md
> +The patient type resource contains information about a patient and their relation to the practice. Examples include new patient, prospect, deceased.
Updated to our min set

2018-10-18 18:48 UTC, VinnieMaida approved these changes
I'm no PartnerAPI expert...but this all seems to make sense to me.

2018-10-18 18:48 UTC, merged